#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.2.2.{build}-{branch}

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2015

clone_depth: 1

nuget:  
  disable_publish_on_pr: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: l3nZXQA47cVHWucS5LK20u28aer1QZT4zcgFo2LZAOn4v1CtRjrXOomdhvJG95bD

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build_script:
- dotnet --info
- dotnet restore --no-cache
- dotnet build **/project.json --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%
- dotnet pack src/Stubbery/project.json --configuration Release --no-build

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
- dotnet test test/Stubbery.IntegrationTests/project.json --configuration Release -f netcoreapp1.0 --no-build
- bash coverage.sh
- bash coveralls.sh

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: src/**/*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  provider: NuGet
  api_key:
    secure: UrYYF7dW4tZvlgTcihdNHoURAdjBRAFUvbXO+Pt+772aQLVNtbjlDBY4BqvHBxcz
  skip_symbols: false
  artifact: /.*\.nupkg/
